### PR TITLE
Add support for latest stable and rework README.md

### PR DESCRIPTION
**Pull request by stich86**
hi @ghhccghk,

i've fixed the patch file and update the commit it to latest 2.0.0. Update also readme, sorry if there are some error in language, feel free to fix it :)

### CODE REVIEW

**Comment by ghhccghk** [comment]
Someone actually came to update, thanks, I will wait until I get off work to see if it can work properly. In addition, the mainline openwrt package has been submitted by someone, I am waiting for my fm350-gl to arrive to debug esim and design the control interface

**Comment by stich86** [comment]
> Someone actually came to update, thanks, I will wait until I get off work to see if it can work properly. In addition, the mainline openwrt package has been submitted by someone, I am waiting for my fm350-gl to arrive to debug esim and design the control interface

i've done a fork of libqmi-wrapper from @z3ntu here https://github.com/stich86/lpac-libmbim-wrapper

tested on my Foxconn T99W175 and Quectel RM502Q-GL pushing eSIM profile using mbimcli. But if you are going to add it directly in lpac without a wrapper will be nice :)

**Comment by ghhccghk** [comment]
> > Someone actually came to update, thanks, I will wait until I get off work to see if it can work properly. In addition, the mainline openwrt package has been submitted by someone, I am waiting for my fm350-gl to arrive to debug esim and design the control interface
> 
> i've done a fork of libqmi-wrapper from @z3ntu here https://github.com/stich86/lpac-libmbim-wrapper
> 
> tested on my Foxconn T99W175 and Quectel RM502Q-GL pushing eSIM profile using mbimcli. But if you are going to add it directly in lpac without a wrapper will be nice :)

I plan to encapsulate lpac into luci interface, so that I can manage esim in a very convenient way

**Comment by stich86** [comment]
> > > Someone actually came to update, thanks, I will wait until I get off work to see if it can work properly. In addition, the mainline openwrt package has been submitted by someone, I am waiting for my fm350-gl to arrive to debug esim and design the control interface
> > 
> > 
> > i've done a fork of libqmi-wrapper from @z3ntu here https://github.com/stich86/lpac-libmbim-wrapper
> > tested on my Foxconn T99W175 and Quectel RM502Q-GL pushing eSIM profile using mbimcli. But if you are going to add it directly in lpac without a wrapper will be nice :)
> 
> I plan to encapsulate lpac into luci interface, so that I can manage esim in a very convenient way

this will be very nice :)
but you should check if Fibocom support AT commands, because for instance my Quectel has AT commands for eUICC but download profile doesn't work :(
That's why I've used MBIM

**Comment by ghhccghk** [comment]
Delete some text

**Comment by stich86** [comment]
Just for reference, version is 2.0.0 not 1.0.1

**Pull request merged**
